# The URL the site will be built for
base_url = "http://cbzehner.com"

# The site title
title = "Chris Zehner"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Enable a theme for the site
theme = "even"

# Enable taxonomies for the site
taxonomies = [
    { name = "categories", rss = false },
    { name = "tags", rss = false },
]

[extra]
# Hide the banner title by setting it to an empty string
even_title = ""

# Set the navigation options for the site
even_menu = [
    { url = "/", name = "Thoughts" },
    { url = "https://github.com/cbzehner", name = "Code" },
    { url = "/about", name = "About" },
]

# Set the author
author = "Chris Zehner"
